package types

import "time"

type ClientStore interface {
	GetClientByIin(iin string) (*Client, error)
	GetClientById(id int) (*Client, error)
	CreateClient(Client) error
}

type Client struct {
	ID                                 int       `json:"id"`
	Name                               string    `json:"name"`
	PrivateFirstName                   string    `json:"privateFirstName"`
	PrivateLastName                    string    `json:"privateLastName"`
	IdentificationNo                   string    `json:"identificationNo"`
	Phone                              string    `json:"phone"`
	Email                              string    `json:"email"`
	ClientType                         string    `json:"clientType"`
	CreatedAt                          time.Time `json:"createdAt"`
	UpdatedAt                          time.Time `json:"updatedAt"`
	Sex                                string    `json:"sex"`
	PermitNotifications                bool      `json:"permitNotifications"`
	Locale                             string    `json:"locale"`
	Address                            string    `json:"address"`
	AddressDeclared                    string    `json:"addressDeclared"`
	Phone2                             string    `json:"phone2"`
	BankID                             int       `json:"bankId"`
	BankAccount                        string    `json:"bankAccount"`
	Income                             int       `json:"income"`
	OfficialIncome                     int       `json:"officialIncome"`
	BusinessIncome                     int       `json:"businessIncome"`
	Debts                              string    `json:"debts"`
	DebtsAmount                        int       `json:"debtsAmount"`
	DebtsAmountSecondary               int       `json:"debtsAmountSecondary"`
	Region                             string    `json:"region"`
	RegionDeclared                     string    `json:"regionDeclared"`
	AgreementSigner                    string    `json:"agreementSigner"`
	Address2                           string    `json:"address2"`
	Comment                            string    `json:"comment"`
	IP                                 string    `json:"ip"`
	AdditionalIncome                   int       `json:"additionalIncome"`
	HouseholdExpenses                  int       `json:"householdExpenses"`
	MonthlyLiabilities                 int       `json:"monthlyLiabilities"`
	MonthlyLiabilitiesSecondary        int       `json:"monthlyLiabilitiesSecondary"`
	PhotoUID                           string    `json:"photoUid"`
	AdditionalIncomeFoundation         string    `json:"additionalIncomeFoundation"`
	SaisInformation                    int       `json:"saisInformation"`
	DateOfBirth                        time.Time `json:"dateOfBirth"`
	VatNo                              string    `json:"vatNo"`
	SodraRequestTime                   time.Time `json:"sodraRequestTime"`
	GrtRequestTime                     time.Time `json:"grtRequestTime"`
	XroadRrRequestTime                 time.Time `json:"xroadRrRequestTime"`
	PhoneNotes                         string    `json:"phoneNotes"`
	Phone2Notes                        string    `json:"phone2Notes"`
	AverageIncome                      int       `json:"averageIncome"`
	Workplace                          string    `json:"workplace"`
	WorkExperience                     string    `json:"workExperience"`
	DriversLicenceNo                   string    `json:"driversLicenceNo"`
	DriverName                         string    `json:"driverName"`
	DriverIdentificationNo             string    `json:"driverIdentificationNo"`
	DriverPhone                        string    `json:"driverPhone"`
	DriverEmail                        string    `json:"driverEmail"`
	DriverAddress                      string    `json:"driverAddress"`
	MissingDriversLicenceReason        string    `json:"missingDriversLicenceReason"`
	SaisInformationFull                int       `json:"saisInformationFull"`
	RemoteClientID                     int       `json:"remoteClientId"`
	SpouseID                           int       `json:"spouseId"`
	SpouseStatus                       string    `json:"spouseStatus"`
	SpouseHash                         string    `json:"spouseHash"`
	SpouseVerificationType             string    `json:"spouseVerificationType"`
	SpouseVerificationManual           bool      `json:"spouseVerificationManual"`
	SpouseStatusForDti                 string    `json:"spouseStatusForDti"`
	WorkplaceAddress                   string    `json:"workplaceAddress"`
	WorkplacePhone                     string    `json:"workplacePhone"`
	IDCardDateOfIssuance               time.Time `json:"idCardDateOfIssuance"`
	IDCardDateOfExpire                 time.Time `json:"idCardDateOfExpire"`
	IDCardIssuedBy                     string    `json:"idCardIssuedBy"`
	SocialCardID                       string    `json:"socialCardId"`
	SecondName                         string    `json:"secondName"`
	AddressMunicipality                string    `json:"addressMunicipality"`
	AddressCity                        string    `json:"addressCity"`
	AddressBuilding                    string    `json:"addressBuilding"`
	AddressApartment                   string    `json:"addressApartment"`
	AddressPostalCode                  string    `json:"addressPostalCode"`
	AddressCountry                     string    `json:"addressCountry"`
	AddressDeclaredCountry             string    `json:"addressDeclaredCountry"`
	AddressDeclaredMunicipality        string    `json:"addressDeclaredMunicipality"`
	AddressDeclaredCity                string    `json:"addressDeclaredCity"`
	AddressDeclaredBuilding            string    `json:"addressDeclaredBuilding"`
	AddressDeclaredApartment           string    `json:"addressDeclaredApartment"`
	AddressDeclaredPostalCode          string    `json:"addressDeclaredPostalCode"`
	APIAccessToken                     string    `json:"apiAccessToken"`
	PhoneConfirmed                     bool      `json:"phoneConfirmed"`
	EmailConfirmed                     bool      `json:"emailConfirmed"`
	MiscData                           string    `json:"miscData"`
	UnconfirmedEmail                   string    `json:"unconfirmedEmail"`
	UnconfirmedPhone                   string    `json:"unconfirmedPhone"`
	Phone3                             string    `json:"phone3"`
	Phone4                             string    `json:"phone4"`
	Phone3Notes                        string    `json:"phone3Notes"`
	Phone4Notes                        string    `json:"phone4Notes"`
	ProtectedByGdpr                    bool      `json:"protectedByGdpr"`
	IDCardNumber                       string    `json:"idCardNumber"`
	PassportNumber                     string    `json:"passportNumber"`
	PassportDateOfIssuance             time.Time `json:"passportDateOfIssuance"`
	PassportDateOfExpire               time.Time `json:"passportDateOfExpire"`
	PassportIssuedBy                   string    `json:"passportIssuedBy"`
	RubieID                            int       `json:"rubieId"`
	RiskLevel                          string    `json:"riskLevel"`
	Charity                            bool      `json:"charity"`
	PassportSeries                     string    `json:"passportSeries"`
	IsCitizen                          bool      `json:"isCitizen"`
	PlaceOfBirth                       string    `json:"placeOfBirth"`
	BankMfo                            string    `json:"bankMfo"`
	PassportType                       string    `json:"passportType"`
	PassportIssueRegion                string    `json:"passportIssueRegion"`
	PassportIssueMunicipality          string    `json:"passportIssueMunicipality"`
	StateRegistrationNumber            string    `json:"stateRegistrationNumber"`
	StateRegistrationDate              time.Time `json:"stateRegistrationDate"`
	OrganizationOkpo                   string    `json:"organizationOkpo"`
	OrganizationDirectorName           string    `json:"organizationDirectorName"`
	OrganizationFormOfOwnership        string    `json:"organizationFormOfOwnership"`
	OrganizationIndustryTopSection     string    `json:"organizationIndustryTopSection"`
	OrganizationIndustrySection        string    `json:"organizationIndustrySection"`
	OrganizationIndustryGroup          string    `json:"organizationIndustryGroup"`
	OrganizationIndustryClass          string    `json:"organizationIndustryClass"`
	OrganizationIndustryName           string    `json:"organizationIndustryName"`
	RentObject                         string    `json:"rentObject"`
	Phone2Confirmed                    bool      `json:"phone2Confirmed"`
	Phone3Confirmed                    bool      `json:"phone3Confirmed"`
	Phone4Confirmed                    bool      `json:"phone4Confirmed"`
	AddressDeclaredConfirmed           bool      `json:"addressDeclaredConfirmed"`
	PropertyConfirmed                  bool      `json:"propertyConfirmed"`
	VehicleConfirmed                   bool      `json:"vehicleConfirmed"`
	UsesOnlinePaymentSystem            bool      `json:"usesOnlinePaymentSystem"`
	PhoneRegistrationDate              time.Time `json:"phoneRegistrationDate"`
	WorkSubdivision                    string    `json:"workSubdivision"`
	WorkPosition                       string    `json:"workPosition"`
	MarriageCertificate                string    `json:"marriageCertificate"`
	DateOfReceiptMarriageCertificate   time.Time `json:"dateOfReceiptMarriageCertificate"`
	RegistryOfficeName                 string    `json:"registryOfficeName"`
	SpouseIdentificationNumber         string    `json:"spouseIdentificationNumber"`
	ManualAge                          bool      `json:"manualAge"`
	WorkplaceIdentificationNo          string    `json:"workplaceIdentificationNo"`
	WorkplaceEmail                     string    `json:"workplaceEmail"`
	WorkplaceLegalAddress              string    `json:"workplaceLegalAddress"`
	WorkplaceEmploymentDate            time.Time `json:"workplaceEmploymentDate"`
	AverageDebitCardOutcome            int       `json:"averageDebitCardOutcome"`
	RemainingBalance                   int       `json:"remainingBalance"`
	AverageDepositAccountFunding       int       `json:"averageDepositAccountFunding"`
	AverageWithdrawnFromDepositAccount int       `json:"averageWithdrawnFromDepositAccount"`
	MonthlyBankCardFunding             int       `json:"monthlyBankCardFunding"`
	Kdn                                float64   `json:"kdn"`
	PkbIncome                          int       `json:"pkbIncome"`
	TotalMonthlyPaymentFromPkb         int       `json:"totalMonthlyPaymentFromPkb"`
	CreatedAtInTbm                     time.Time `json:"createdAtInTbm"`
}

type RegisterClientPayload struct {
	IdentificationNo string `json:"identificationNo" validate:"required"`
	Phone            string `json:"phone" validate:"required"`
	Email            string `json:"email" validate:"required,email"`
	Password         string `json:"password" validate:"required,min=3,max=130"`
}

/*
	Name                               string    `json:"name"`
	PrivateFirstName                   string    `json:"privateFirstName"`
	PrivateLastName                    string    `json:"privateLastName"`
	IdentificationNo                   string    `json:"IdentificationNo"`
	Phone                              string    `json:"phone"`
	Email                              string    `json:"email"`
	ClientType                         string    `json:"clientType"`
	CreatedAt                          time.Time `json:"createdAt"`
	UpdatedAt                          time.Time `json:"updatedAt"`
	Sex                                string    `json:"sex"`
	PermitNotifications                bool      `json:"permitNotifications"`
	Locale                             string    `json:"locale"`
	Address                            string    `json:"address"`
	AddressDeclared                    string    `json:"addressDeclared"`
	Phone2                             string    `json:"phone2"`
	BankID                             int       `json:"bankId"`
	BankAccount                        string    `json:"bankAccount"`
	Income                             int       `json:"income"`
	OfficialIncome                     int       `json:"officialIncome"`
	BusinessIncome                     int       `json:"businessIncome"`
	Debts                              string    `json:"debts"`
	DebtsAmount                        int       `json:"debtsAmount"`
	DebtsAmountSecondary               int       `json:"debtsAmountSecondary"`
	Region                             string    `json:"region"`
	RegionDeclared                     string    `json:"regionDeclared"`
	AgreementSigner                    string    `json:"agreementSigner"`
	Address2                           string    `json:"address2"`
	Comment                            string    `json:"comment"`
	IP                                 string    `json:"ip"`
	AdditionalIncome                   int       `json:"additionalIncome"`
	HouseholdExpenses                  int       `json:"householdExpenses"`
	MonthlyLiabilities                 int       `json:"monthlyLiabilities"`
	MonthlyLiabilitiesSecondary        int       `json:"monthlyLiabilitiesSecondary"`
	PhotoUID                           string    `json:"photoUid"`
	AdditionalIncomeFoundation         string    `json:"additionalIncomeFoundation"`
	SaisInformation                    int       `json:"saisInformation"`
	DateOfBirth                        time.Time `json:"dateOfBirth"`
	VatNo                              string    `json:"vatNo"`
	SodraRequestTime                   time.Time `json:"sodraRequestTime"`
	GrtRequestTime                     time.Time `json:"grtRequestTime"`
	XroadRrRequestTime                 time.Time `json:"xroadRrRequestTime"`
	PhoneNotes                         string    `json:"phoneNotes"`
	Phone2Notes                        string    `json:"phone2Notes"`
	AverageIncome                      int       `json:"averageIncome"`
	Workplace                          string    `json:"workplace"`
	WorkExperience                     string    `json:"workExperience"`
	DriversLicenceNo                   string    `json:"driversLicenceNo"`
	DriverName                         string    `json:"driverName"`
	DriverIdentificationNo             string    `json:"driverIdentificationNo"`
	DriverPhone                        string    `json:"driverPhone"`
	DriverEmail                        string    `json:"driverEmail"`
	DriverAddress                      string    `json:"driverAddress"`
	MissingDriversLicenceReason        string    `json:"missingDriversLicenceReason"`
	SaisInformationFull                int       `json:"saisInformationFull"`
	RemoteClientID                     int       `json:"remoteClientId"`
	SpouseID                           int       `json:"spouseId"`
	SpouseStatus                       string    `json:"spouseStatus"`
	SpouseHash                         string    `json:"spouseHash"`
	SpouseVerificationType             string    `json:"spouseVerificationType"`
	SpouseVerificationManual           bool      `json:"spouseVerificationManual"`
	SpouseStatusForDti                 string    `json:"spouseStatusForDti"`
	WorkplaceAddress                   string    `json:"workplaceAddress"`
	WorkplacePhone                     string    `json:"workplacePhone"`
	IDCardDateOfIssuance               time.Time `json:"idCardDateOfIssuance"`
	IDCardDateOfExpire                 time.Time `json:"idCardDateOfExpire"`
	IDCardIssuedBy                     string    `json:"idCardIssuedBy"`
	SocialCardID                       string    `json:"socialCardId"`
	SecondName                         string    `json:"secondName"`
	AddressMunicipality                string    `json:"addressMunicipality"`
	AddressCity                        string    `json:"addressCity"`
	AddressBuilding                    string    `json:"addressBuilding"`
	AddressApartment                   string    `json:"addressApartment"`
	AddressPostalCode                  string    `json:"addressPostalCode"`
	AddressCountry                     string    `json:"addressCountry"`
	AddressDeclaredCountry             string    `json:"addressDeclaredCountry"`
	AddressDeclaredMunicipality        string    `json:"addressDeclaredMunicipality"`
	AddressDeclaredCity                string    `json:"addressDeclaredCity"`
	AddressDeclaredBuilding            string    `json:"addressDeclaredBuilding"`
	AddressDeclaredApartment           string    `json:"addressDeclaredApartment"`
	AddressDeclaredPostalCode          string    `json:"addressDeclaredPostalCode"`
	APIAccessToken                     string    `json:"apiAccessToken"`
	PhoneConfirmed                     bool      `json:"phoneConfirmed"`
	EmailConfirmed                     bool      `json:"emailConfirmed"`
	MiscData                           string    `json:"miscData"`
	UnconfirmedEmail                   string    `json:"unconfirmedEmail"`
	UnconfirmedPhone                   string    `json:"unconfirmedPhone"`
	Phone3                             string    `json:"phone3"`
	Phone4                             string    `json:"phone4"`
	Phone3Notes                        string    `json:"phone3Notes"`
	Phone4Notes                        string    `json:"phone4Notes"`
	ProtectedByGdpr                    bool      `json:"protectedByGdpr"`
	IDCardNumber                       string    `json:"idCardNumber"`
	PassportNumber                     string    `json:"passportNumber"`
	PassportDateOfIssuance             time.Time `json:"passportDateOfIssuance"`
	PassportDateOfExpire               time.Time `json:"passportDateOfExpire"`
	PassportIssuedBy                   string    `json:"passportIssuedBy"`
	RubieID                            int       `json:"rubieId"`
	RiskLevel                          string    `json:"riskLevel"`
	Charity                            bool      `json:"charity"`
	PassportSeries                     string    `json:"passportSeries"`
	IsCitizen                          bool      `json:"isCitizen"`
	PlaceOfBirth                       string    `json:"placeOfBirth"`
	BankMfo                            string    `json:"bankMfo"`
	PassportType                       string    `json:"passportType"`
	PassportIssueRegion                string    `json:"passportIssueRegion"`
	PassportIssueMunicipality          string    `json:"passportIssueMunicipality"`
	StateRegistrationNumber            string    `json:"stateRegistrationNumber"`
	StateRegistrationDate              time.Time `json:"stateRegistrationDate"`
	OrganizationOkpo                   string    `json:"organizationOkpo"`
	OrganizationDirectorName           string    `json:"organizationDirectorName"`
	OrganizationFormOfOwnership        string    `json:"organizationFormOfOwnership"`
	OrganizationIndustryTopSection     string    `json:"organizationIndustryTopSection"`
	OrganizationIndustrySection        string    `json:"organizationIndustrySection"`
	OrganizationIndustryGroup          string    `json:"organizationIndustryGroup"`
	OrganizationIndustryClass          string    `json:"organizationIndustryClass"`
	OrganizationIndustryName           string    `json:"organizationIndustryName"`
	RentObject                         string    `json:"rentObject"`
	Phone2Confirmed                    bool      `json:"phone2Confirmed"`
	Phone3Confirmed                    bool      `json:"phone3Confirmed"`
	Phone4Confirmed                    bool      `json:"phone4Confirmed"`
	AddressDeclaredConfirmed           bool      `json:"addressDeclaredConfirmed"`
	PropertyConfirmed                  bool      `json:"propertyConfirmed"`
	VehicleConfirmed                   bool      `json:"vehicleConfirmed"`
	UsesOnlinePaymentSystem            bool      `json:"usesOnlinePaymentSystem"`
	PhoneRegistrationDate              time.Time `json:"phoneRegistrationDate"`
	WorkSubdivision                    string    `json:"workSubdivision"`
	WorkPosition                       string    `json:"workPosition"`
	MarriageCertificate                string    `json:"marriageCertificate"`
	DateOfReceiptMarriageCertificate   time.Time `json:"dateOfReceiptMarriageCertificate"`
	RegistryOfficeName                 string    `json:"registryOfficeName"`
	SpouseIdentificationNumber         string    `json:"spouseIdentificationNumber"`
	ManualAge                          bool      `json:"manualAge"`
	WorkplaceIdentificationNo          string    `json:"workplaceIdentificationNo"`
	WorkplaceEmail                     string    `json:"workplaceEmail"`
	WorkplaceLegalAddress              string    `json:"workplaceLegalAddress"`
	WorkplaceEmploymentDate            time.Time `json:"workplaceEmploymentDate"`
	AverageDebitCardOutcome            int       `json:"averageDebitCardOutcome"`
	RemainingBalance                   int       `json:"remainingBalance"`
	AverageDepositAccountFunding       int       `json:"averageDepositAccountFunding"`
	AverageWithdrawnFromDepositAccount int       `json:"averageWithdrawnFromDepositAccount"`
	MonthlyBankCardFunding             int       `json:"monthlyBankCardFunding"`
	Kdn                                float64   `json:"kdn"`
	PkbIncome                          int       `json:"pkbIncome"`
	TotalMonthlyPaymentFromPkb         int       `json:"totalMonthlyPaymentFromPkb"`
	CreatedAtInTbm                     time.Time `json:"createdAtInTbm"`
*/
